import { NextResponse } from 'next/server';
import {
  FileText,
  BarChart2,
  Zap,
  Sparkles,
  ClipboardList,
  Gamepad2,
  MessageSquare,
  AlertTriangle,
  Send,
  Wrench,
  Link2,
  Waves,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const dynamic = 'force-dynamic';

export const INTEGRATION_ICONS: Record<string, LucideIcon> = {
  notion: FileText,
  airtable: BarChart2,
  zapier: Zap,
  make: Sparkles,
  'google-sheets': ClipboardList,
  discord: Gamepad2,
  slack: MessageSquare,
  pagerduty: AlertTriangle,
  telegram: Send,
  n8n: Wrench,
  ifttt: Link2,
  pipedream: Waves,
};

export const INTEGRATIONS = [
  {
    id: 'notion',
    name: 'Notion',
    emoji: '📝',
    description:
      'Relay-required recipe for mapping an eligible TradeClaw webhook payload into the Notion API. This is not a native integration.',
    category: 'Productivity',
    categoryColor: 'blue',
    tags: ['database', 'notes', 'kanban'],
    setupSteps: [
      'Open Notion and go to Settings → Integrations → New Integration.',
      'Name it "TradeClaw" and grant read/write database permissions.',
      'Copy the Internal Integration Token from Notion.',
      'Share your target database with the integration.',
      'Build an HTTPS relay that validates TradeClaw, stores the Notion token server-side, and calls the Notion API.',
      'Configure the relay URL in TradeClaw Webhook Settings and verify it with signal.test.',
    ],
    payload: {
      symbol: 'BTCUSD',
      direction: 'BUY',
      timeframe: 'H4',
      confidence: 82,
      price: 67420.5,
      rsi: 38.2,
      macd: 0.0012,
      timestamp: '2026-03-28T09:00:00Z',
    },
  },
  {
    id: 'airtable',
    name: 'Airtable',
    emoji: '📊',
    description:
      'Relay-required recipe for transforming an eligible TradeClaw webhook payload into an authenticated Airtable API request.',
    category: 'Productivity',
    categoryColor: 'blue',
    tags: ['spreadsheet', 'database', 'reports'],
    setupSteps: [
      'Log into Airtable → go to account → API → Generate API Key.',
      'Create a new base called "TradeClaw Signals" with columns: Symbol, Direction, Confidence, Price, Timestamp.',
      'Copy your Base ID from the Airtable API docs URL.',
      'Build an HTTPS relay that stores Airtable credentials server-side and maps the TradeClaw payload to Airtable records.',
      'Add the relay URL in TradeClaw Webhook Settings and verify it with signal.test.',
    ],
    payload: {
      symbol: 'XAUUSD',
      direction: 'SELL',
      timeframe: 'D1',
      confidence: 74,
      price: 2345.8,
      rsi: 71.5,
      timestamp: '2026-03-28T09:00:00Z',
    },
  },
  {
    id: 'zapier',
    name: 'Zapier',
    emoji: '⚡',
    description: 'Manual recipe for using Webhooks by Zapier as a destination for authenticated TradeClaw dispatches.',
    category: 'Dev Tools',
    categoryColor: 'orange',
    tags: ['automation', 'webhook recipe', 'manual setup'],
    setupSteps: [
      'Go to zapier.com and click "Create Zap".',
      'Choose "Webhooks by Zapier" as the trigger app and select "Catch Hook".',
      'Zapier will generate a unique webhook URL — copy it.',
      'Paste the Zapier webhook URL into TradeClaw Settings → Webhooks.',
      'Set up your action (e.g., send Gmail, update Google Sheet, post to Slack).',
    ],
    payload: {
      symbol: 'ETHUSD',
      direction: 'BUY',
      timeframe: 'H1',
      confidence: 79,
      price: 3512.0,
      indicators: { rsi: 42.1, macd: 0.0008, ema_cross: 'bullish' },
      timestamp: '2026-03-28T09:00:00Z',
    },
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    emoji: '🔮',
    description: 'Manual recipe for receiving an eligible TradeClaw webhook in a Make custom-webhook scenario.',
    category: 'Dev Tools',
    categoryColor: 'orange',
    tags: ['visual automation', 'flows', 'conditional'],
    setupSteps: [
      'Sign up at make.com and create a new Scenario.',
      'Add a "Webhooks" module as the trigger and select "Custom webhook".',
      'Make will generate a unique webhook URL — copy it.',
      'Paste it into TradeClaw Settings → Webhooks.',
      'Add action modules: filter by direction, send to Telegram, log to Google Sheets, etc.',
    ],
    payload: {
      symbol: 'GBPUSD',
      direction: 'SELL',
      timeframe: 'H4',
      confidence: 68,
      price: 1.2745,
      timestamp: '2026-03-28T09:00:00Z',
    },
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    emoji: '📋',
    description: 'Manual Apps Script receiver recipe for mapping delivered TradeClaw payloads into a Google Sheet.',
    category: 'Productivity',
    categoryColor: 'blue',
    tags: ['spreadsheet', 'logging', 'charts'],
    setupSteps: [
      'In Google Sheets, go to Extensions → Apps Script.',
      'Paste the doPost(e) script that appends signal data to the sheet.',
      'Deploy as a Web App with access set to "Anyone".',
      'Copy the deployment URL.',
      'Add this URL as a webhook in TradeClaw Settings → Webhooks.',
    ],
    payload: {
      symbol: 'EURUSD',
      direction: 'BUY',
      timeframe: 'H1',
      confidence: 85,
      price: 1.0892,
      rsi: 36.4,
      timestamp: '2026-03-28T09:00:00Z',
    },
  },
  {
    id: 'discord',
    name: 'Discord',
    emoji: '🎮',
    description:
      'Direct-webhook recipe. TradeClaw formats Discord embeds when an eligible dispatch targets a Discord webhook URL.',
    category: 'Communication',
    categoryColor: 'purple',
    tags: ['chat', 'alerts', 'community'],
    setupSteps: [
      'In your Discord server, go to Channel Settings → Integrations → Webhooks.',
      'Click "New Webhook", name it "TradeClaw Signals", and choose the target channel.',
      'Copy the webhook URL.',
      'Paste it into TradeClaw Settings → Webhooks.',
      'Use signal.test to verify formatting. Entry-like signal.new delivery remains evidence-gated.',
    ],
    payload: {
      embeds: [
        {
          title: '🟢 BUY Signal — BTCUSD H4',
          color: 3066993,
          fields: [
            { name: 'Confidence', value: '82%', inline: true },
            { name: 'Price', value: '$67,420', inline: true },
            { name: 'RSI', value: '38.2', inline: true },
          ],
          timestamp: '2026-03-28T09:00:00Z',
        },
      ],
    },
  },
  {
    id: 'slack',
    name: 'Slack',
    emoji: '💬',
    description:
      'Direct-webhook recipe. TradeClaw formats Block Kit when an eligible dispatch targets a Slack incoming-webhook URL.',
    category: 'Communication',
    categoryColor: 'purple',
    tags: ['team', 'notifications', 'blocks'],
    setupSteps: [
      'Go to api.slack.com/apps and click "Create New App".',
      'Enable "Incoming Webhooks" and activate it for your workspace.',
      'Click "Add New Webhook to Workspace" and pick your channel.',
      'Copy the webhook URL.',
      'Paste it into TradeClaw Webhook Settings, then verify with signal.test. Entry-like signal.new delivery remains evidence-gated.',
    ],
    payload: {
      blocks: [
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: '*🟢 BUY — BTCUSD H4*\nConfidence: 82% | Price: $67,420',
          },
        },
      ],
    },
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty',
    emoji: '🚨',
    description:
      'Relay-required example for mapping a TradeClaw event into PagerDuty Events API v2. Confidence is not a severity guarantee.',
    category: 'Dev Tools',
    categoryColor: 'orange',
    tags: ['alerting', 'on-call', 'incident management'],
    setupSteps: [
      'Log into PagerDuty and navigate to Services → Add New Service.',
      'Choose "Events API v2" as the integration type and save.',
      'Copy the Integration Key (routing key).',
      'Use the PagerDuty Events API URL: https://events.pagerduty.com/v2/enqueue',
      'Build a relay that stores the routing key, applies your severity policy, and calls PagerDuty Events API v2.',
      'Configure the relay URL in TradeClaw Webhook Settings and verify it explicitly.',
    ],
    payload: {
      routing_key: 'your_integration_key',
      event_action: 'trigger',
      payload: {
        summary: 'CRITICAL: BTCUSD BUY signal — 92% confidence',
        severity: 'critical',
        source: 'tradeclaw',
        custom_details: { symbol: 'BTCUSD', confidence: 92, rsi: 22.1 },
      },
    },
  },
  {
    id: 'telegram',
    name: 'Telegram',
    emoji: '✈️',
    description: 'Relay-required example for mapping a TradeClaw webhook payload into Telegram Bot API sendMessage.',
    category: 'Communication',
    categoryColor: 'purple',
    tags: ['messaging', 'mobile', 'alerts'],
    setupSteps: [
      'Open Telegram and search for @BotFather.',
      'Send /newbot and follow the prompts to create your bot.',
      'Copy the bot token from BotFather.',
      'Get your chat ID by messaging @userinfobot.',
      'Build a relay that stores the bot token, formats the message, and calls Telegram Bot API sendMessage.',
      'Configure the relay URL in TradeClaw Webhook Settings and verify it explicitly.',
    ],
    payload: {
      chat_id: 'your_chat_id',
      text: '🟢 *BUY — BTCUSD H4*\nConfidence: 82%\nPrice: $67,420\nRSI: 38.2',
      parse_mode: 'Markdown',
    },
  },
  {
    id: 'n8n',
    name: 'n8n',
    emoji: '🔧',
    description: 'Manual recipe for receiving eligible TradeClaw webhook deliveries in a self-hosted n8n workflow.',
    category: 'Dev Tools',
    categoryColor: 'orange',
    tags: ['self-hosted', 'automation', 'open-source'],
    setupSteps: [
      'Deploy n8n via Docker: docker run -d -p 5678:5678 n8nio/n8n',
      'Open n8n at http://localhost:5678 and create a new workflow.',
      'Add a "Webhook" node as the trigger and set HTTP Method to POST.',
      'Copy the webhook URL from the node.',
      'Paste it into TradeClaw Settings → Webhooks and activate the n8n workflow.',
    ],
    payload: {
      symbol: 'XAUUSD',
      direction: 'BUY',
      timeframe: 'H4',
      confidence: 88,
      price: 2310.5,
      timestamp: '2026-03-28T09:00:00Z',
    },
  },
  {
    id: 'ifttt',
    name: 'IFTTT',
    emoji: '🔗',
    description:
      "Manual IFTTT webhook recipe. Verify that your applet accepts and maps TradeClaw's standard JSON payload.",
    category: 'Dev Tools',
    categoryColor: 'orange',
    tags: ['simple', 'smart home', 'mobile'],
    setupSteps: [
      'Go to ifttt.com and create a new Applet.',
      'For the "If This" trigger, choose "Webhooks" → "Receive a web request".',
      'Set the event name to "tradeclaw_signal" and save.',
      'Go to Webhooks settings and copy your unique IFTTT key.',
      'Use URL: https://maker.ifttt.com/trigger/tradeclaw_signal/with/key/{YOUR_KEY}',
    ],
    payload: {
      value1: 'BTCUSD',
      value2: 'BUY',
      value3: '82',
    },
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    emoji: '🌊',
    description: 'Manual recipe for receiving eligible TradeClaw webhook deliveries in a Pipedream HTTP workflow.',
    category: 'Dev Tools',
    categoryColor: 'orange',
    tags: ['developer', 'code', 'APIs'],
    setupSteps: [
      'Sign up at pipedream.com and click "New Workflow".',
      'Add an HTTP / Webhook trigger as the first step.',
      'Pipedream generates a unique webhook URL — copy it.',
      'Paste it into TradeClaw Settings → Webhooks.',
      'Add code steps to filter, transform, or route signals to any downstream API.',
    ],
    payload: {
      symbol: 'ETHUSD',
      direction: 'SELL',
      timeframe: 'D1',
      confidence: 76,
      price: 3200.0,
      rsi: 69.8,
      indicators: { macd: -0.0015, bb_position: 'upper' },
      timestamp: '2026-03-28T09:00:00Z',
    },
  },
];

export async function GET() {
  try {
    return NextResponse.json({
      integrations: INTEGRATIONS.map(({ id, name, emoji, description, category, categoryColor, tags }) => ({
        id,
        name,
        emoji,
        description,
        category,
        categoryColor,
        tags,
      })),
      total: INTEGRATIONS.length,
      catalogType: 'manual-setup-recipes',
      configurationPath: '/settings/webhooks',
    });
  } catch {
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
