import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Data Freshness — TradeClaw',
  description: 'How TradeClaw exposes provider provenance, timestamps, cache behavior, and unavailable states without promising fixed market-data latency.',
};

interface FreshnessRow {
  surface: string;
  timing: string;
  evidence: string;
}

const ROWS: FreshnessRow[] = [
  {
    surface: 'Quotes and prices',
    timing: 'Provider and client polling intervals vary by deployment.',
    evidence: 'Each returned quote includes its runtime source. Missing provider data is omitted; hardcoded prices are not substituted.',
  },
  {
    surface: 'OHLCV candles and indicators',
    timing: 'Bounded by the upstream candle close and the operator schedule.',
    evidence: 'Public candidates require provider-backed candles. OHLCV marked synthetic is excluded from signal generation and MTF scoring.',
  },
  {
    surface: 'Signal candidates',
    timing: 'Generated by requests or configured jobs; no fixed publication SLA.',
    evidence: 'Use the candidate timestamp, candle source, data-quality field, and persisted gate decision. A rule score is not a calibrated probability.',
  },
  {
    surface: '4h and 24h outcomes',
    timing: 'Available only after the relevant observation window and a successful verifier run.',
    evidence: 'Outcomes are resolved against provider OHLCV. They are unsized price observations, not broker fills or portfolio returns.',
  },
  {
    surface: 'Badges, feeds, and embeds',
    timing: 'HTTP and CDN caches can outlive the client polling interval.',
    evidence: 'Consumers should display the source timestamp and an unavailable or stale state. Empty data must not become a neutral fixture.',
  },
  {
    surface: 'Telegram, email, push, and webhooks',
    timing: 'Best effort after a configured job runs; no delivery-time guarantee.',
    evidence: 'Entry-like delivery requires a persisted approval plus the current cost-adjusted evidence gate. Provider or gate failure blocks fan-out.',
  },
  {
    surface: 'Backtests and paper simulation',
    timing: 'Computed on demand from the selected data and assumptions.',
    evidence: 'Backtests are modeled. Paper fills require explicit observed prices and modeled slippage; neither is live broker performance.',
  },
];

export default function DataFreshnessPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-16">
      <header className="mb-10">
        <p className="mb-3 text-xs font-mono uppercase text-[var(--text-secondary)]">Transparency</p>
        <h1 className="mb-4 text-3xl font-bold text-[var(--foreground)] sm:text-4xl">Data freshness and provenance</h1>
        <p className="max-w-3xl leading-relaxed text-[var(--text-secondary)]">
          TradeClaw does not promise a universal “real-time” cadence. Upstream markets, providers, caches, configured jobs, and client polling all have separate clocks. Inspect the timestamp and source attached to the specific value you are using.
        </p>
      </header>

      <section className="mb-10 rounded-lg border border-amber-500/25 bg-amber-500/5 p-5 text-sm text-[var(--text-secondary)]">
        A page refresh time is not a market-data timestamp. A polling interval is not a delivery SLA. When provenance or required data is unavailable, production surfaces should show an empty or unavailable state instead of generated market values.
      </section>

      <section className="overflow-hidden rounded-lg border border-[var(--border)]">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[680px] text-left text-sm">
            <thead className="bg-[var(--bg-card)] text-xs uppercase text-[var(--text-secondary)]">
              <tr>
                <th className="px-4 py-3">Surface</th>
                <th className="px-4 py-3">Timing boundary</th>
                <th className="px-4 py-3">What to verify</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--border)]">
              {ROWS.map((row) => (
                <tr key={row.surface} className="align-top">
                  <td className="px-4 py-4 font-medium text-[var(--foreground)]">{row.surface}</td>
                  <td className="px-4 py-4 text-[var(--text-secondary)]">{row.timing}</td>
                  <td className="px-4 py-4 text-[var(--text-secondary)]">{row.evidence}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mt-10 space-y-3 text-sm leading-relaxed text-[var(--text-secondary)]">
        <h2 className="text-lg font-semibold text-[var(--foreground)]">Operational check</h2>
        <p>Before relying on a value, verify its provider, observation timestamp, data-quality label, gate scope, and whether the endpoint returned a stale or unavailable condition.</p>
        <p>The repository documents intended schedules, but the deployed operator controls credentials and jobs. Production behavior must be established from the current response and deployment logs, not from a marketing cadence.</p>
      </section>

      <footer className="mt-12 border-t border-[var(--border)] pt-6 text-xs text-[var(--text-secondary)]">
        Review the <Link href="/methodology" className="underline">methodology</Link>, <Link href="/proof" className="underline">proof status</Link>, and <Link href="/open-data" className="underline">open data</Link> before drawing a performance conclusion.
      </footer>
    </main>
  );
}
